# Generated by Django 3.2.3 on 2021-05-19 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, verbose_name='Club Name')),
                ('dateCreated', models.DateField(default=django.utils.timezone.now)),
                ('convener', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Convener', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
