# Generated by Django 3.2.3 on 2021-05-19 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0003_alter_club_convener'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Item Name')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_club', to='Club.club')),
            ],
        ),
    ]
