# Generated by Django 3.2.3 on 2021-05-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0006_itemrequest_requeststatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrequest',
            name='requested',
            field=models.IntegerField(default=1, verbose_name='Number of requested items '),
            preserve_default=False,
        ),
    ]
