# Generated by Django 3.2.3 on 2021-05-20 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0007_itemrequest_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrequest',
            name='club',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Club.club'),
            preserve_default=False,
        ),
    ]
