# Generated by Django 3.2.3 on 2021-05-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('userName', models.CharField(max_length=27, unique=True, verbose_name='Username')),
                ('email', models.CharField(max_length=27, unique=True, verbose_name='Email Address')),
                ('name', models.CharField(max_length=27, verbose_name='First Name')),
                ('year', models.IntegerField(choices=[(1, 'First Year'), (2, 'Second Year'), (3, 'Third Year'), (4, 'Fourth Year')], default=2, unique=True, verbose_name='Year')),
                ('roll', models.CharField(max_length=10, verbose_name='Roll Number')),
                ('department', models.CharField(max_length=20, verbose_name='Department')),
                ('mobileNumber', models.CharField(max_length=27, unique=True, verbose_name='Mobile Number')),
                ('is_convener', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
