# Generated by Django 3.2.3 on 2021-05-19 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0005_alter_items_name'),
        ('User', '0003_alter_user_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='club',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Club_Member', to='Club.club'),
        ),
    ]
